const data = [
  [
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 0,
      Word_tally: 0,
      Total_words: 10,
      Target: "After",
      Distractor: "x-x-x",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 1,
      Word_tally: 1,
      Total_words: 10,
      Target: "a",
      Distractor: "so",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 2,
      Word_tally: 2,
      Total_words: 10,
      Target: "bit",
      Distractor: "pot",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 3,
      Word_tally: 3,
      Total_words: 10,
      Target: "of",
      Distractor: "if",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 4,
      Word_tally: 4,
      Total_words: 10,
      Target: "success",
      Distractor: "singing",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 5,
      Word_tally: 5,
      Total_words: 10,
      Target: "the",
      Distractor: "ate",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 6,
      Word_tally: 6,
      Total_words: 10,
      Target: "stocks",
      Distractor: "winter",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 7,
      Word_tally: 7,
      Total_words: 10,
      Target: "took",
      Distractor: "walk",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 8,
      Word_tally: 8,
      Total_words: 10,
      Target: "a",
      Distractor: "we",
    },
    {
      Story_num: 0,
      Sentence_num: 0,
      Word_num: 9,
      Word_tally: 9,
      Total_words: 10,
      Target: "dive",
      Distractor: "toad",
    },
  ],
  [
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 0,
      Word_tally: 0,
      Total_words: 9,
      Target: "The",
      Distractor: "x-x-x",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 1,
      Word_tally: 1,
      Total_words: 9,
      Target: "fashion",
      Distractor: "realize",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 2,
      Word_tally: 2,
      Total_words: 9,
      Target: "model",
      Distractor: "shirt",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 3,
      Word_tally: 3,
      Total_words: 9,
      Target: "was",
      Distractor: "see",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 4,
      Word_tally: 4,
      Total_words: 9,
      Target: "very",
      Distractor: "into",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 5,
      Word_tally: 5,
      Total_words: 9,
      Target: "self-conscious",
      Distractor: "professionally",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 6,
      Word_tally: 6,
      Total_words: 9,
      Target: "of",
      Distractor: "do",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 7,
      Word_tally: 7,
      Total_words: 9,
      Target: "her",
      Distractor: "why",
    },
    {
      Story_num: 1,
      Sentence_num: 1,
      Word_num: 8,
      Word_tally: 8,
      Total_words: 9,
      Target: "appearance",
      Distractor: "sandwiches",
    },
  ],
];
